import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import io

# ═══════════════════════════════════════════════════════════════
# PAGE CONFIGURATION
# ═══════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Enhanced Monorail LCA/LCCA Assessment Tool",
    page_icon="🚝",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ═══════════════════════════════════════════════════════════════
# CHEN 2022 BENCHMARK - EXTERNAL COMPARISON ONLY
# Reference: Chen, J., Wang, H., Li, X. (2022)
# DOI: 10.1155/2022/3872069 | Journal: Complexity (Hindawi)
# Used only for benchmark validation.
# No Chen calibration factors are used in the core LCA/LCCA model.
# ═══════════════════════════════════════════════════════════════

CHEN_2022_BENCHMARK = {
    'reference': {
        'title': 'Quantifying Carbon Emissions Generated by Monorail Transits: A Life Cycle Assessment Approach',
        'authors': 'Chen, J., Wang, H., Li, X.',
        'journal': 'Complexity (Hindawi)',
        'year': 2022,
        'doi': '10.1155/2022/3872069',
        'quartile': 'Q2',
        'license': 'CC BY 4.0 (Open Access)',
        'verification': 'Peer-reviewed scientific publication'
    },
    'system_parameters': {
        'length_km': 96,
        'lifetime_years': 100,
        'functional_unit': '1 passenger-km',
        'system_boundary': 'Cradle-to-grave'
    },
    'material_intensity_per_km': {
        'concrete_m3': 7291.67,
        'steel_tons': 1041.67,
        'aluminum_tons': 52.08,
        'unit': 'per km'
    },
    'embodied_impact_per_km': {
        'energy_GJ': 55982,
        'carbon_tons_CO2': 4662,
        'unit': 'per km'
    },
    'operational_performance': {
        'energy_kwh_per_pkm': 0.088,
        'carbon_kgCO2_per_pkm': 0.0352,
        'unit': 'per passenger-km'
    }
}

# ═══════════════════════════════════════════════════════════════
# REFERENCE VALUES
# ═══════════════════════════════════════════════════════════════
REF_CONCRETE = 700000
REF_STEEL = 100000
REF_ALUMINUM = 10000
REF_WOOD = 2000
REF_FRP = 1000
REF_GLASS = 500
REF_LENGTH = 96

# ═══════════════════════════════════════════════════════════════
# MATERIAL EMBODIED ENERGY AND CARBON FACTORS
# Energy factors (MJ/kg): Hammond & Jones (2008) / ICE v2.0,
# used only where embodied energy is reported in legacy ICE tables.
# Carbon factors (kgCO2e/kg): ICE Database / EPD / selected dataset
# at A1-A3 cradle-to-gate boundary.
# Every factor includes: source, version, material category, boundary, status.
# ═══════════════════════════════════════════════════════════════
MATERIAL_FACTORS = {
    "concrete_rc25_30": {
        "ee_mj_per_kg": 0.91,
        "gwp_kgco2e_per_kg": 0.131,
        "source": "Hammond & Jones (2008), ICE v2.0 summary tables",
        "version": "ICE v2.0 (energy) + selected carbon dataset",
        "material_category": "Concrete RC25/30",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-CONC-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    },
    "steel_structural": {
        "ee_mj_per_kg": 20.10,
        "gwp_kgco2e_per_kg": 1.55,
        "source": "ICE Database v4.1 (Oct 2025), structural steel section, dataset documented in supplementary material",
        "version": "ICE-aligned project dataset",
        "material_category": "Structural steel section",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-STEEL-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    },
    "aluminum_general": {
        "ee_mj_per_kg": 155.0,
        "gwp_kgco2e_per_kg": 9.16,
        "source": "ICE Database v4.1 (Oct 2025), primary aluminum category, dataset documented in supplementary material",
        "version": "ICE-aligned project dataset",
        "material_category": "Primary aluminum",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-AL-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    },
    "wood_general": {
        "ee_mj_per_kg": 10.0,
        "gwp_kgco2e_per_kg": 0.40,
        "source": "EPD International library, timber generic declaration (documented in supplementary material)",
        "version": "Supplementary dataset S1 (material-factor audit table)",
        "material_category": "Timber generic",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-WOOD-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    },
    "frp_general": {
        "ee_mj_per_kg": 95.0,
        "gwp_kgco2e_per_kg": 6.50,
        "source": "EPD-based FRP composite generic declaration (documented in supplementary material)",
        "version": "Supplementary dataset S1 (material-factor audit table)",
        "material_category": "FRP composite",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-FRP-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    },
    "glass_primary": {
        "ee_mj_per_kg": 15.0,
        "gwp_kgco2e_per_kg": 0.91,
        "source": "ICE Database v4.1 (Oct 2025), flat glass category, dataset documented in supplementary material",
        "version": "ICE-aligned project dataset",
        "material_category": "Flat glass",
        "boundary": "A1-A3 / cradle-to-gate",
        "source_id": "S1-GLASS-001",
        "declared_unit": "1 kg",
        "status": "verified_if_S1_is_attached"
    }
}



MATERIAL_FACTOR_AUDIT = pd.DataFrame([
    {
        "material": key,
        "ee_mj_per_kg": val["ee_mj_per_kg"],
        "gwp_kgco2e_per_kg": val["gwp_kgco2e_per_kg"],
        "source": val["source"],
        "source_id": val.get("source_id", "not specified"),
        "declared_unit": val.get("declared_unit", "1 kg"),
        "version": val["version"],
        "material_category": val["material_category"],
        "boundary": val["boundary"],
        "status": val["status"],
    }
    for key, val in MATERIAL_FACTORS.items()
])

RECYCLING_CREDIT_SCENARIOS = {
    "none": {
        "steel": {"energy_credit_fraction": 0.0, "carbon_credit_fraction": 0.0},
        "aluminum": {"energy_credit_fraction": 0.0, "carbon_credit_fraction": 0.0},
        "source": "No end-of-life credit scenario"
    },
    "conservative": {
        "steel": {"energy_credit_fraction": 0.35, "carbon_credit_fraction": 0.30},
        "aluminum": {"energy_credit_fraction": 0.50, "carbon_credit_fraction": 0.50},
        "source": "Scenario assumption; use for sensitivity only"
    },
    "base": {
        "steel": {"energy_credit_fraction": 0.70, "carbon_credit_fraction": 0.65},
        "aluminum": {"energy_credit_fraction": 0.85, "carbon_credit_fraction": 0.90},
        "source": "Scenario assumption; requires EPD/EoL allocation evidence before final publication"
    }
}

UNCERTAINTY_FACTORS = {
    "concrete_factor": {"cv": 0.10, "source": "Scenario assumption; replace with EPD/database uncertainty before final statistical claims"},
    "steel_factor": {"cv": 0.08, "source": "Scenario assumption; replace with EPD/database uncertainty before final statistical claims"},
    "energy_factor": {"cv": 0.15, "source": "Scenario assumption; replace with measured operational uncertainty before final statistical claims"},
    "grid_carbon_factor": {"cv": 0.12, "source": "Scenario assumption; replace with grid-factor uncertainty before final statistical claims"}
}

TRANSPORT_EMISSION_FACTORS = {"truck":0.10,"rail":0.03,"ship":0.015}

# ═══════════════════════════════════════════════════════════════
# MATERIAL DENSITIES (kg/m³)
# ═══════════════════════════════════════════════════════════════
DENSITIES = {
    'concrete': 2400,
    'wood': 600,
    'steel': 7850,
    'aluminum': 2700,
    'frp': 1850,
    'glass': 2500,
    'glass_surface': 10
}


# ═══════════════════════════════════════════════════════════════
# SCIENTIFIC CALCULATION FUNCTIONS
# ═══════════════════════════════════════════════════════════════


def calculate_intensity_score(value, ref_value, min_scale=0.5, max_scale=1.5):
    """Calculate intensity score based on reference value"""
    intensity = value / ref_value
    if intensity < min_scale:
        return 100 * (1 - (min_scale - intensity) / min_scale)
    elif intensity > max_scale:
        return 100 * (1 - (intensity - max_scale) / max_scale)
    else:
        return 100


def calculate_material_score_integrated(material_data):
    """Integrated material score with recycling bonuses"""
    concrete_intensity = material_data['concrete_intensity']
    steel_intensity = material_data['steel_intensity']
    aluminum_intensity = material_data['aluminum_intensity']
    wood_intensity = material_data['wood_intensity']
    frp_intensity = material_data['frp_intensity']
    glass_intensity = material_data['glass_intensity']

    steel_recycle_bonus = material_data['steel_recycle_rate'] / 100.0 * 0.05
    aluminum_recycle_bonus = material_data['aluminum_recycle_rate'] / 100.0 * 0.05
    recycling_bonus = steel_recycle_bonus + aluminum_recycle_bonus

    base_material_score = (
        0.30 * concrete_intensity +
        0.30 * steel_intensity +
        0.20 * aluminum_intensity +
        0.10 * wood_intensity +
        0.05 * frp_intensity +
        0.05 * glass_intensity
    )

    material_score = min(100.0, base_material_score * (1.0 + recycling_bonus))
    return material_score


def calculate_environmental_display_score(env_data):
    """Heuristic environmental display score (not ISO LCA result)."""
    operational_co2 = env_data['operational_co2']
    embodied_co2 = env_data['embodied_co2']
    renewable_share = env_data['renewable_share']
    noise_reduction = env_data['noise_reduction']
    land_efficiency = env_data['land_efficiency']

    renewable_mitigation_factor = 1.0 - (renewable_share / 100.0) * 0.40
    adjusted_operational_co2 = operational_co2 * renewable_mitigation_factor

    land_efficiency_bonus = (land_efficiency / 5000.0) * 0.15
    land_efficiency_bonus = np.clip(land_efficiency_bonus, 0, 0.15)
    adjusted_embodied_co2 = embodied_co2 * (1.0 - land_efficiency_bonus)

    total_co2_adjusted = adjusted_operational_co2 + adjusted_embodied_co2

    noise_quality_multiplier = 1.0 + (noise_reduction / 15.0) * 0.10
    noise_quality_multiplier = np.clip(noise_quality_multiplier, 1.0, 1.10)

    co2_normalized = (total_co2_adjusted - 5000.0) / (50000.0 - 5000.0)
    co2_normalized = np.clip(co2_normalized, 0, 1)
    co2_score = (1.0 - co2_normalized) * 100.0

    environmental_score = co2_score * noise_quality_multiplier
    environmental_score = np.clip(environmental_score, 0, 100)
    return float(environmental_score)


def calculate_operational_score_integrated(op_data):
    """Integrated operational score with internal coupling effects"""
    time_savings = op_data['time_savings']
    availability = op_data['availability']
    land_efficiency = op_data['land_efficiency']
    energy_efficiency = op_data['energy_per_pax_km']

    availability_factor = availability / 100.0
    effective_time_savings = time_savings * availability_factor
    time_score = min(100.0, (effective_time_savings / 2500.0) * 100.0)

    energy_bonus = (0.20 - energy_efficiency) / 0.20
    energy_bonus = np.clip(energy_bonus, 0, 1)

    adjusted_land_efficiency = land_efficiency * (1.0 + energy_bonus * 0.20)
    land_score = min(100.0, (adjusted_land_efficiency / 5000.0) * 100.0)

    synergy_multiplier = 1.0 + (availability_factor * float(energy_bonus) * 0.10)
    availability_score = availability * synergy_multiplier
    availability_score = min(100.0, availability_score)

    operational_score = (
        time_score * 0.40 +
        availability_score * 0.40 +
        land_score * 0.20
    )

    operational_score = np.clip(operational_score, 0, 100)
    return float(operational_score)


def calculate_economic_score_integrated(econ_data):
    """Heuristic economic display score using NPV-LCC-aware cost efficiency."""
    construction_cost = econ_data['construction_cost']
    npv_lcc_m = econ_data['npv_lcc_m']
    jobs_created = econ_data['jobs_created']
    economic_multiplier = econ_data['economic_multiplier']

    jobs_per_million = jobs_created / max(construction_cost, 1.0)
    job_efficiency_bonus = min(1.0, jobs_per_million / 2.0) * 0.15

    lcc_ratio = npv_lcc_m / max(construction_cost, 1.0)
    cost_efficiency_score = 100.0 / (1.0 + max(lcc_ratio - 1.0, 0.0))
    cost_efficiency_score = min(100.0, cost_efficiency_score * (1.0 + job_efficiency_bonus))

    total_economic_impact = jobs_created * economic_multiplier
    jobs_score = min(100.0, (total_economic_impact / 12000.0) * 100.0)

    multiplier_score = min(100.0, (economic_multiplier / 3.5) * 100.0)

    economic_score = (
        jobs_score * 0.50 +
        cost_efficiency_score * 0.30 +
        multiplier_score * 0.20
    )

    economic_score = np.clip(economic_score, 0, 100)
    return float(economic_score)


def calculate_cross_category_interactions(mat_score, env_score, op_score, econ_score):
    """Calculate cross-category interaction effects (synergies and trade-offs)"""
    mat_norm = mat_score / 100.0
    env_norm = env_score / 100.0
    op_norm = op_score / 100.0
    econ_norm = econ_score / 100.0

    # Heuristic interaction visualization only.
    # Coefficients are illustrative and are not validated causal effects.
    interaction_matrix = {
        'mat_to_env': -0.25,
        'env_to_op': 0.15,
        'op_to_econ': 0.30,
        'econ_to_mat': 0.20,
        'mat_to_op': 0.10,
        'env_to_econ': -0.15
    }

    interaction_effects = {
        'mat_env_effect': mat_norm * interaction_matrix['mat_to_env'] * 100,
        'env_op_effect': env_norm * interaction_matrix['env_to_op'] * 100,
        'op_econ_effect': op_norm * interaction_matrix['op_to_econ'] * 100,
        'econ_mat_effect': econ_norm * interaction_matrix['econ_to_mat'] * 100,
        'mat_op_effect': mat_norm * interaction_matrix['mat_to_op'] * 100,
        'env_econ_effect': env_norm * interaction_matrix['env_to_econ'] * 100
    }

    adjusted_material_score = mat_score + interaction_effects['econ_mat_effect']
    adjusted_environmental_score = env_score + interaction_effects['mat_env_effect']
    adjusted_operational_score = (op_score +
                                   interaction_effects['env_op_effect'] +
                                   interaction_effects['mat_op_effect'])
    adjusted_economic_score = (econ_score +
                                interaction_effects['op_econ_effect'] +
                                interaction_effects['env_econ_effect'])

    adjusted_material_score = float(np.clip(adjusted_material_score, 0, 100))
    adjusted_environmental_score = float(np.clip(adjusted_environmental_score, 0, 100))
    adjusted_operational_score = float(np.clip(adjusted_operational_score, 0, 100))
    adjusted_economic_score = float(np.clip(adjusted_economic_score, 0, 100))

    total_synergy = sum([abs(effect) for key, effect in interaction_effects.items() if effect > 0])
    total_tradeoff = sum([abs(effect) for key, effect in interaction_effects.items() if effect < 0])

    synergy_ratio = total_synergy / max(total_tradeoff, 0.01)

    return {
        'adjusted_material_score': adjusted_material_score,
        'adjusted_environmental_score': adjusted_environmental_score,
        'adjusted_operational_score': adjusted_operational_score,
        'adjusted_economic_score': adjusted_economic_score,
        'interaction_effects': interaction_effects,
        'total_synergy': total_synergy,
        'total_tradeoff': total_tradeoff,
        'synergy_ratio': synergy_ratio
    }



ASSESSMENT_LIFETIME_YEARS = 50


def calculate_a4_transport_co2(material_masses_kg, distance_km, mode):
    ef = TRANSPORT_EMISSION_FACTORS.get(mode, TRANSPORT_EMISSION_FACTORS["truck"])
    total_mass_tons = sum(material_masses_kg.values()) / 1000.0
    return total_mass_tons * distance_km * ef / 1000.0


def calculate_lca_summary(embodied_co2_tons, annual_operational_co2_tons, embodied_energy_mj,
                          annual_operational_energy_kwh, daily_pax_km, lifetime_years,
                          a4_transport_co2_tons=0.0):
    lifetime_operational_co2_tons = annual_operational_co2_tons * lifetime_years
    total_lifecycle_co2_tons = embodied_co2_tons + a4_transport_co2_tons + lifetime_operational_co2_tons
    lifetime_pax_km = daily_pax_km * 365 * lifetime_years
    co2_kg_per_pkm = (total_lifecycle_co2_tons * 1000 / lifetime_pax_km) if lifetime_pax_km > 0 else np.nan

    return {
        "scope": "Partial process-based LCA: A1-A3 materials + optional A4 transport + B6 operation",
        "embodied_co2_tons": embodied_co2_tons,
        "a4_transport_co2_tons": a4_transport_co2_tons,
        "annual_operational_co2_tons": annual_operational_co2_tons,
        "lifetime_operational_co2_tons": lifetime_operational_co2_tons,
        "total_lifecycle_co2_tons": total_lifecycle_co2_tons,
        "co2_kg_per_pkm": co2_kg_per_pkm,
        "embodied_energy_mj": embodied_energy_mj,
        "annual_operational_energy_kwh": annual_operational_energy_kwh,
        "lifetime_operational_energy_kwh": annual_operational_energy_kwh * lifetime_years,
        "lifetime_pax_km": lifetime_pax_km,
        "stage_coverage": {
            "A1_A3_materials": "included",
            "A4_transport": "included" if a4_transport_co2_tons > 0 else "not included",
            "A5_construction": "not included",
            "B2_B5_maintenance_replacement": "not included",
            "B6_operation": "included",
            "C1_C4_end_of_life": "not included"
        }
    }


def calculate_lcc_npv(construction_cost_m, annual_maintenance_m, annual_energy_cost_m=0.0,
                      replacement_costs=None, end_of_life_cost_m=0.0, residual_value_m=0.0,
                      discount_rate_pct=5.0, lifetime_years=50):
    r = discount_rate_pct / 100.0
    n = lifetime_years
    replacement_costs = replacement_costs or {}

    def pv_single(cost, year):
        return cost / ((1 + r) ** year) if r > 0 else cost

    upv = (1 - (1 + r) ** (-n)) / r if r > 0 else n

    pv_maintenance = annual_maintenance_m * upv
    pv_energy = annual_energy_cost_m * upv
    pv_replacement = sum(pv_single(cost, year) for year, cost in replacement_costs.items())
    pv_end_of_life = pv_single(end_of_life_cost_m, n)
    pv_residual = pv_single(residual_value_m, n)

    npv_lcc = construction_cost_m + pv_maintenance + pv_energy + pv_replacement + pv_end_of_life - pv_residual

    return {"npv_lcc_m": npv_lcc, "discount_rate_pct": discount_rate_pct, "lifetime_years": n}

def run_full_assessment(params):
    """Run the complete assessment with all calculations - exact replica of original"""
    # Material calculations
    concrete_m3 = params['concrete'] * 1000
    concrete_kg = concrete_m3 * DENSITIES['concrete']
    steel_tons = params['steel'] * 1000
    steel_kg = steel_tons * 1000
    aluminum_tons = params['aluminum'] * 1000
    aluminum_kg = aluminum_tons * 1000
    wood_m3 = params['wood'] * 1000
    wood_kg = wood_m3 * DENSITIES['wood']
    frp_tons = params['frp'] * 1000
    frp_kg = frp_tons * 1000
    glass_m2 = params['glass'] * 1000
    glass_kg = glass_m2 * DENSITIES['glass_surface']

    material_masses_kg = {"concrete": concrete_kg, "steel": steel_kg, "aluminum": aluminum_kg, "wood": wood_kg, "frp": frp_kg, "glass": glass_kg}
    a4_transport_co2_tons = calculate_a4_transport_co2(material_masses_kg, params.get("transport_distance_km", 0.0), params.get("transport_mode", "truck"))

    # Material intensity scores
    concrete_intensity = calculate_intensity_score(concrete_m3, REF_CONCRETE)
    steel_intensity = calculate_intensity_score(steel_tons, REF_STEEL)
    aluminum_intensity = calculate_intensity_score(aluminum_tons, REF_ALUMINUM)
    wood_intensity = calculate_intensity_score(wood_m3, REF_WOOD)
    frp_intensity = calculate_intensity_score(frp_tons, REF_FRP)
    glass_intensity = calculate_intensity_score(glass_m2, REF_GLASS)

    # Operational Energy & Carbon (core model, no external calibration factors)
    energy_per_pax_km_raw = params['energy_per_pax']
    daily_pax_km = params['daily_pax_km'] * 1000
    carbon_intensity = params['carbon_intensity']
    renewable_share = params['renewable_share']

    energy_per_pax_km_calibrated = energy_per_pax_km_raw
    annual_operational_energy = energy_per_pax_km_calibrated * daily_pax_km * 365

    effective_carbon_intensity = carbon_intensity * (1 - renewable_share / 100.0)
    operational_carbon_intensity = energy_per_pax_km_calibrated * effective_carbon_intensity
    calibrated_carbon_intensity = operational_carbon_intensity
    annual_co2_operational = calibrated_carbon_intensity * daily_pax_km * 365 / 1000

    steel_recycle_rate = params['steel_recycle'] / 100.0
    recycling_scenario = params.get("recycling_scenario", "none")
    recycling_factors = RECYCLING_CREDIT_SCENARIOS[recycling_scenario]
    aluminum_recycle_rate = params['aluminum_recycle'] / 100.0

    # Embodied Energy
    ee_concrete = concrete_kg * MATERIAL_FACTORS['concrete_rc25_30']['ee_mj_per_kg']
    ee_steel = steel_kg * MATERIAL_FACTORS['steel_structural']['ee_mj_per_kg']
    ee_aluminum = aluminum_kg * MATERIAL_FACTORS['aluminum_general']['ee_mj_per_kg']
    ee_wood = wood_kg * MATERIAL_FACTORS['wood_general']['ee_mj_per_kg']
    ee_frp = frp_kg * MATERIAL_FACTORS['frp_general']['ee_mj_per_kg']
    ee_glass = glass_kg * MATERIAL_FACTORS['glass_primary']['ee_mj_per_kg']

    steel_recycling_credit_ee = ee_steel * (params['steel_recycle'] / 100) * recycling_factors['steel']['energy_credit_fraction']
    aluminum_recycling_credit_ee = ee_aluminum * (params['aluminum_recycle'] / 100) * recycling_factors['aluminum']['energy_credit_fraction']

    total_ee = (ee_concrete + ee_steel + ee_aluminum +
                ee_wood + ee_frp + ee_glass -
                steel_recycling_credit_ee - aluminum_recycling_credit_ee)

    # Embodied Carbon
    carbon_concrete = concrete_kg * MATERIAL_FACTORS['concrete_rc25_30']['gwp_kgco2e_per_kg']
    carbon_steel = steel_kg * MATERIAL_FACTORS['steel_structural']['gwp_kgco2e_per_kg']
    carbon_aluminum = aluminum_kg * MATERIAL_FACTORS['aluminum_general']['gwp_kgco2e_per_kg']
    carbon_wood = wood_kg * MATERIAL_FACTORS['wood_general']['gwp_kgco2e_per_kg']
    carbon_frp = frp_kg * MATERIAL_FACTORS['frp_general']['gwp_kgco2e_per_kg']
    carbon_glass = glass_kg * MATERIAL_FACTORS['glass_primary']['gwp_kgco2e_per_kg']

    steel_recycling_credit_c = carbon_steel * (params['steel_recycle'] / 100) * recycling_factors['steel']['carbon_credit_fraction']
    aluminum_recycling_credit_c = carbon_aluminum * (params['aluminum_recycle'] / 100) * recycling_factors['aluminum']['carbon_credit_fraction']

    total_carbon_raw = (carbon_concrete + carbon_steel + carbon_aluminum +
                        carbon_wood + carbon_frp + carbon_glass -
                        steel_recycling_credit_c - aluminum_recycling_credit_c)

    total_embodied_co2 = total_carbon_raw / 1000

    lca_results = calculate_lca_summary(
        embodied_co2_tons=total_embodied_co2,
        annual_operational_co2_tons=annual_co2_operational,
        embodied_energy_mj=total_ee,
        annual_operational_energy_kwh=annual_operational_energy,
        daily_pax_km=daily_pax_km,
        lifetime_years=ASSESSMENT_LIFETIME_YEARS,
        a4_transport_co2_tons=a4_transport_co2_tons
    )
    total_co2 = lca_results["total_lifecycle_co2_tons"]

    # Operational
    daily_time_savings = params['time_savings'] * 1000
    system_availability = params['availability'] / 100

    # Economic
    construction_cost = params['construction_cost']
    annual_maintenance = params['maintenance_cost']
    jobs_created = params['jobs_created']
    economic_multiplier = params['economic_multiplier']
    total_jobs = jobs_created * economic_multiplier
    total_maintenance_cost = annual_maintenance * ASSESSMENT_LIFETIME_YEARS

    lcc_results = calculate_lcc_npv(
        construction_cost_m=construction_cost,
        annual_maintenance_m=annual_maintenance,
        annual_energy_cost_m=params.get("annual_energy_cost", 0.0),
        residual_value_m=params.get("residual_value", 0.0),
        discount_rate_pct=params.get("discount_rate", 5.0),
        lifetime_years=ASSESSMENT_LIFETIME_YEARS
    )

    noise_reduction = params['noise_reduction']
    land_use_efficiency = params['land_use']

    # PHASE 2: Calculate category scores
    material_data = {
        'concrete_intensity': concrete_intensity,
        'steel_intensity': steel_intensity,
        'aluminum_intensity': aluminum_intensity,
        'wood_intensity': wood_intensity,
        'frp_intensity': frp_intensity,
        'glass_intensity': glass_intensity,
        'steel_recycle_rate': params['steel_recycle'],
        'aluminum_recycle_rate': params['aluminum_recycle']
    }
    environmental_data = {
        'operational_co2': annual_co2_operational,
        'embodied_co2': total_embodied_co2,
        'renewable_share': renewable_share,
        'noise_reduction': noise_reduction,
        'land_efficiency': land_use_efficiency
    }
    operational_data = {
        'time_savings': daily_time_savings,
        'availability': params['availability'],
        'land_efficiency': land_use_efficiency,
        'energy_per_pax_km': energy_per_pax_km_calibrated
    }
    economic_data = {
        'construction_cost': construction_cost,
        'npv_lcc_m': lcc_results['npv_lcc_m'],
        'jobs_created': jobs_created,
        'economic_multiplier': economic_multiplier
    }

    material_score = calculate_material_score_integrated(material_data)
    environmental_score = calculate_environmental_display_score(environmental_data)
    operational_score = calculate_operational_score_integrated(operational_data)
    economic_score = calculate_economic_score_integrated(economic_data)

    # PHASE 3: Cross-category interactions
    interaction_results = calculate_cross_category_interactions(
        material_score, environmental_score, operational_score, economic_score
    )

    adjusted_material_score = interaction_results['adjusted_material_score']
    adjusted_environmental_score = interaction_results['adjusted_environmental_score']
    adjusted_operational_score = interaction_results['adjusted_operational_score']
    adjusted_economic_score = interaction_results['adjusted_economic_score']

    heuristic_display_score = (
        material_score * 0.25 +
        environmental_score * 0.30 +
        operational_score * 0.25 +
        economic_score * 0.20
    )
    heuristic_display_score = float(np.clip(heuristic_display_score, 0, 100))

    return {
        'material_score': material_score,
        'environmental_score': environmental_score,
        'operational_score': operational_score,
        'economic_score': economic_score,
        'adjusted_material_score': adjusted_material_score,
        'adjusted_environmental_score': adjusted_environmental_score,
        'adjusted_operational_score': adjusted_operational_score,
        'adjusted_economic_score': adjusted_economic_score,
        'interaction_effects': interaction_results['interaction_effects'],
        'total_synergy': interaction_results['total_synergy'],
        'total_tradeoff': interaction_results['total_tradeoff'],
        'synergy_ratio': interaction_results['synergy_ratio'],
        'heuristic_display_score': heuristic_display_score,
        'overall_score': heuristic_display_score,
        'total_co2': total_co2,
        'annual_co2_operational': annual_co2_operational,
        'total_embodied_co2': total_embodied_co2,
        'effective_carbon_intensity': effective_carbon_intensity,
        'total_ee': total_ee,
        'annual_operational_energy': annual_operational_energy,
        'total_jobs': total_jobs,
        'total_maintenance_cost': total_maintenance_cost,
        'concrete_volume': concrete_m3,
        'steel_mass': steel_kg,
        'aluminum_mass': aluminum_kg,
        'steel_tons': steel_tons,
        'aluminum_tons': aluminum_tons,
        'frp_tons': frp_tons,
        'energy_per_pax_km': energy_per_pax_km_calibrated,
        'operational_carbon_intensity': calibrated_carbon_intensity,
        'daily_pax_km': daily_pax_km,
        'construction_cost': construction_cost,
        'annual_maintenance': annual_maintenance,
        'steel_recycle_rate': steel_recycle_rate * 100,
        'aluminum_recycle_rate': aluminum_recycle_rate * 100,
        'renewable_share': renewable_share,
        'noise_reduction': noise_reduction,
        'land_use_efficiency': land_use_efficiency,
        'sustainability_score': heuristic_display_score,
        'lca_results': lca_results,
        'total_lifecycle_co2': lca_results['total_lifecycle_co2_tons'],
        'co2_kg_per_pkm': lca_results['co2_kg_per_pkm'],
        'lcc_results': lcc_results,
        'npv_lcc_m': lcc_results['npv_lcc_m'],
        'total_cost': lcc_results['npv_lcc_m'] * 1e6,
        'carbon_intensity': carbon_intensity,
        'ee_concrete': ee_concrete,
        'ee_steel': ee_steel,
        'ee_aluminum': ee_aluminum,
        'ee_wood': ee_wood,
        'ee_frp': ee_frp,
        'ee_glass': ee_glass,
        'carbon_concrete': carbon_concrete,
        'carbon_steel': carbon_steel,
        'carbon_aluminum': carbon_aluminum,
        'carbon_wood': carbon_wood,
        'carbon_frp': carbon_frp,
        'carbon_glass': carbon_glass,
    }


# ═══════════════════════════════════════════════════════════════
# CUSTOM CSS STYLING
# ═══════════════════════════════════════════════════════════════
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

    .stApp {
        font-family: 'Inter', sans-serif;
    }

    .main-header {
        background: linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%);
        padding: 2rem 2.5rem;
        border-radius: 16px;
        margin-bottom: 1.5rem;
        box-shadow: 0 8px 32px rgba(0,0,0,0.3);
    }
    .main-header h1 {
        color: #ffffff;
        font-size: 2rem;
        font-weight: 800;
        margin: 0;
        letter-spacing: -0.5px;
    }
    .main-header p {
        color: #a8d8ea;
        font-size: 1rem;
        margin: 0.3rem 0 0 0;
        font-weight: 400;
    }

    .metric-card {
        background: linear-gradient(145deg, #1a1a2e 0%, #16213e 100%);
        border: 1px solid rgba(100, 200, 255, 0.15);
        border-radius: 14px;
        padding: 1.5rem;
        text-align: center;
        box-shadow: 0 4px 20px rgba(0,0,0,0.2);
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .metric-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 8px 30px rgba(0,0,0,0.3);
    }
    .metric-card .metric-value {
        font-size: 2rem;
        font-weight: 800;
        background: linear-gradient(135deg, #00d2ff, #3a7bd5);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin: 0;
    }
    .metric-card .metric-label {
        color: #8892b0;
        font-size: 0.85rem;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 1px;
        margin-top: 0.3rem;
    }
    .metric-card .metric-delta {
        color: #64ffda;
        font-size: 0.8rem;
        margin-top: 0.2rem;
    }

    .score-badge {
        display: inline-block;
        padding: 0.4rem 1.2rem;
        border-radius: 20px;
        font-weight: 700;
        font-size: 0.9rem;
    }
    .score-excellent { background: linear-gradient(135deg, #00b09b, #96c93d); color: white; }
    .score-good { background: linear-gradient(135deg, #f7971e, #ffd200); color: #1a1a2e; }
    .score-poor { background: linear-gradient(135deg, #eb3349, #f45c43); color: white; }

    .interaction-synergy { color: #64ffda; font-weight: 600; }
    .interaction-tradeoff { color: #ff6b6b; font-weight: 600; }

    .info-box {
        background: rgba(100, 255, 218, 0.05);
        border-left: 4px solid #64ffda;
        border-radius: 0 8px 8px 0;
        padding: 1rem 1.5rem;
        margin: 0.5rem 0;
    }

    .stTabs [data-baseweb="tab-list"] {
        gap: 4px;
        background-color: #0a192f;
        border-radius: 12px;
        padding: 4px;
    }
    .stTabs [data-baseweb="tab"] {
        background-color: transparent;
        border-radius: 8px;
        color: #8892b0;
        font-weight: 500;
        padding: 8px 16px;
    }
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #233554, #1a365d) !important;
        color: #64ffda !important;
    }

    div[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #0a192f 0%, #112240 100%);
    }
    div[data-testid="stSidebar"] .stMarkdown h1,
    div[data-testid="stSidebar"] .stMarkdown h2,
    div[data-testid="stSidebar"] .stMarkdown h3 {
        color: #ccd6f6;
    }

    .report-box {
        background: #0a192f;
        border: 1px solid #233554;
        border-radius: 12px;
        padding: 1.5rem;
        font-family: 'Consolas', 'Courier New', monospace;
        font-size: 0.85rem;
        color: #a8b2d1;
        white-space: pre-wrap;
        max-height: 600px;
        overflow-y: auto;
    }
</style>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════
# HEADER
# ═══════════════════════════════════════════════════════════════
st.markdown("""
<div class="main-header">
    <h1>🚝 Enhanced Monorail Sustainability Assessment Tool</h1>
    <p>Process-based Partial LCA + NPV-based LCCA Framework | ISO 14040/14044 + ASTM E917 | Cairo University</p>
</div>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════
# SIDEBAR - INPUT PARAMETERS (WRAPPED IN FORM TO MIMIC TKINTER RUN)
# ═══════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 📊 Input Parameters")
    
    with st.form("assessment_form"):
        st.markdown("### 📦 Materials")
        concrete = st.number_input("Concrete (1000 m³)", value=700.0, min_value=0.0, step=10.0, key="concrete")
        steel = st.number_input("Steel (1000 tons)", value=100.0, min_value=0.0, step=5.0, key="steel")
        aluminum = st.number_input("Aluminum (1000 tons)", value=5.0, min_value=0.0, step=0.5, key="aluminum")
        wood = st.number_input("Wood (1000 m³)", value=2.0, min_value=0.0, step=0.5, key="wood")
        frp = st.number_input("FRP (1000 tons)", value=1.0, min_value=0.0, step=0.1, key="frp")
        glass = st.number_input("Glass (1000 m²)", value=0.5, min_value=0.0, step=0.1, key="glass")

        st.markdown("### 🚚 A4 Transport")
        transport_distance_km = st.number_input("Average material transport distance (km)", value=50.0, min_value=0.0, step=10.0, key="transport_distance")
        transport_mode = st.selectbox("Transport mode", ["truck", "rail", "ship"], index=0, key="transport_mode")

        st.markdown("### ♻️ Recycling Rates")
        steel_recycle = st.slider("Steel Recycling (%)", 0, 100, 70, key="steel_recycle")
        aluminum_recycle = st.slider("Aluminum Recycling (%)", 0, 100, 85, key="aluminum_recycle")
        recycling_scenario = st.selectbox("EoL Recycling Credit Scenario", ["none", "conservative", "base"], index=0, key="recycling_scenario")

        st.markdown("### 🌍 Environmental")
        carbon_intensity_input = st.number_input("Grid Carbon (kg CO₂/kWh)", value=0.5, min_value=0.0, step=0.05, key="carbon_int")
        renewable_share = st.slider("Renewable Energy (%)", 0, 100, 20, key="renewable")
        land_use = st.number_input("Land Use (pass/ha)", value=5000.0, min_value=0.0, step=100.0, key="land_use")
        noise_reduction = st.number_input("Noise Reduction (dB)", value=10.0, min_value=0.0, step=1.0, key="noise")

        st.markdown("### ⚙️ Operational")
        energy_per_pax = st.number_input("Energy (kWh/pax-km)", value=0.15, min_value=0.0, step=0.01, format="%.3f", key="energy")
        daily_pax_km = st.number_input("Daily Pax-km (1000)", value=500.0, min_value=0.0, step=10.0, key="daily_pax")
        time_savings = st.number_input("Time Savings (1000h)", value=2.5, min_value=0.0, step=0.1, key="time_sav")
        availability = st.slider("Availability (%)", 0, 100, 98, key="avail")

        st.markdown("### 💰 Economic")
        construction_cost = st.number_input("Construction ($M)", value=2500.0, min_value=0.0, step=50.0, key="const_cost")
        maintenance_cost = st.number_input("Maintenance ($M/yr)", value=50.0, min_value=0.0, step=5.0, key="maint_cost")
        jobs_created = st.number_input("Jobs Created", value=5000.0, min_value=0.0, step=100.0, key="jobs")
        economic_multiplier = st.number_input("Economic Multiplier", value=2.5, min_value=1.0, step=0.1, key="econ_mult")
        discount_rate = st.number_input("Discount Rate for LCC (%)", value=5.0, min_value=0.0, max_value=20.0, step=0.5, key="discount_rate")
        annual_energy_cost = st.number_input("Annual Energy Cost ($M/yr)", value=0.0, min_value=0.0, step=1.0, key="energy_cost")
        residual_value = st.number_input("Residual / Salvage Value at End of Life ($M)", value=0.0, min_value=0.0, step=10.0, key="residual_value")

        st.markdown("---")
        run_btn = st.form_submit_button("🚀 RUN ASSESSMENT", type="primary", use_container_width=True)

# Collect parameters
current_params = {
    'concrete': concrete, 'steel': steel, 'aluminum': aluminum,
    'wood': wood, 'frp': frp, 'glass': glass,
    'steel_recycle': steel_recycle, 'aluminum_recycle': aluminum_recycle, 'recycling_scenario': recycling_scenario,
    'transport_distance_km': transport_distance_km, 'transport_mode': transport_mode,
    'carbon_intensity': carbon_intensity_input, 'renewable_share': renewable_share,
    'land_use': land_use, 'noise_reduction': noise_reduction,
    'energy_per_pax': energy_per_pax, 'daily_pax_km': daily_pax_km,
    'time_savings': time_savings, 'availability': availability,
    'construction_cost': construction_cost, 'maintenance_cost': maintenance_cost,
    'jobs_created': jobs_created, 'economic_multiplier': economic_multiplier,
    'discount_rate': discount_rate, 'annual_energy_cost': annual_energy_cost,
    'residual_value': residual_value
}

@st.cache_data
def run_full_assessment_cached(params_tuple):
    params = dict(params_tuple)
    return run_full_assessment(params)

# Run assessment on button click or auto-run for the first time
if run_btn or 'results' not in st.session_state:
    params_tuple = tuple(sorted(current_params.items()))
    st.session_state['results'] = run_full_assessment_cached(params_tuple)
    st.session_state['params'] = current_params
    # No direct st.session_state assignments for widget keys to prevent StreamlitAPIException
results = st.session_state['results']
params = st.session_state['params']

with st.sidebar.expander("📊 Dashboard-only Heuristic Score", expanded=False):
    st.info("This score is for interface visualization only and is not used as an ISO LCA/LCCA result.")
    st.metric("Heuristic Display Score", f"{results['heuristic_display_score']:.1f}/100")

with st.expander("🧩 LCA Stage Coverage", expanded=False):
    coverage = results["lca_results"]["stage_coverage"]
    coverage_df = pd.DataFrame([
        {"Stage": k, "Status": v} for k, v in coverage.items()
    ])
    st.dataframe(coverage_df, use_container_width=True, hide_index=True)

# ═══════════════════════════════════════════════════════════════
# MAIN CONTENT - TABS (10 TABS like original)
# ═══════════════════════════════════════════════════════════════
tabs = st.tabs([
    "📊 Results & Analysis",
    "🔬 Benchmark & Validation",
    "🎯 Pareto Optimization",
    "📈 12-Element Analysis",
    "🎲 Uncertainty Analysis",
    "📐 3D Sensitivity Surface",
    "📊 Sensitivity Analysis",
    "🗺️ Urban Analytics",
    "🔄 Interaction Network",
    "📖 About & Methodology"
])

# ═══════════════════════════════════════════════════════════════
# TAB 1: RESULTS & ANALYSIS
# ═══════════════════════════════════════════════════════════════
with tabs[0]:
    # Key metrics row
    m1, m2, m3, m4, m5 = st.columns(5)
    with m1:
        co2_pkm = results['co2_kg_per_pkm']
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{co2_pkm:.4f}</div>
            <div class="metric-label">kg CO₂e / passenger-km</div>
            <div class="metric-delta">Scientific LCA indicator</div>
        </div>""", unsafe_allow_html=True)
    with m2:
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{results['total_lifecycle_co2']:,.0f}</div>
            <div class="metric-label">Total CO₂ (tons)</div>
            <div class="metric-delta">Embodied: {results['lca_results']['embodied_co2_tons']:,.0f}t</div>
        </div>""", unsafe_allow_html=True)
    with m3:
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{results['total_ee']/1000:,.0f}</div>
            <div class="metric-label">Embodied Energy (GJ)</div>
            <div class="metric-delta">Annual Op: {results['annual_operational_energy']:,.0f} kWh</div>
        </div>""", unsafe_allow_html=True)
    with m4:
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">${results['npv_lcc_m']:,.0f}M</div>
            <div class="metric-label">LCC NPV Cost</div>
            <div class="metric-delta">Jobs: {results['total_jobs']:,.0f}</div>
        </div>""", unsafe_allow_html=True)
    with m5:
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{params['renewable_share']}%</div>
            <div class="metric-label">Renewable Energy</div>
            <div class="metric-delta">Carbon: {results['effective_carbon_intensity']:.3f} kg/kWh</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("---")

    # Category Scores Comparison
    col_scores1, col_scores2 = st.columns(2)

    with col_scores1:
        st.markdown("#### 📊 Category Scores (Original vs Adjusted)")
        categories = ['Material', 'Environmental', 'Operational', 'Economic']
        original = [results['material_score'], results['environmental_score'],
                     results['operational_score'], results['economic_score']]
        adjusted = [results['adjusted_material_score'], results['adjusted_environmental_score'],
                     results['adjusted_operational_score'], results['adjusted_economic_score']]

        fig_scores = go.Figure()
        fig_scores.add_trace(go.Bar(name='Original', x=categories, y=original,
                                     marker_color='rgba(100, 149, 237, 0.7)',
                                     text=[f'{v:.1f}' for v in original], textposition='outside'))
        fig_scores.add_trace(go.Bar(name='Interaction-Adjusted', x=categories, y=adjusted,
                                     marker_color='rgba(100, 255, 218, 0.7)',
                                     text=[f'{v:.1f}' for v in adjusted], textposition='outside'))
        fig_scores.update_layout(
            barmode='group', height=400,
            plot_bgcolor='rgba(10,25,47,0.8)', paper_bgcolor='rgba(0,0,0,0)',
            font_color='#ccd6f6', yaxis_range=[0, 110],
            yaxis_title='Score (0-100)', margin=dict(t=30, b=30)
        )
        st.plotly_chart(fig_scores, use_container_width=True)

    with col_scores2:
        st.markdown("#### 🕸️ Sustainability Radar")
        fig_radar = go.Figure()
        fig_radar.add_trace(go.Scatterpolar(
            r=adjusted + [adjusted[0]],
            theta=categories + [categories[0]],
            fill='toself', fillcolor='rgba(100, 255, 218, 0.15)',
            line=dict(color='#64ffda', width=2), name='Adjusted'
        ))
        fig_radar.add_trace(go.Scatterpolar(
            r=original + [original[0]],
            theta=categories + [categories[0]],
            fill='toself', fillcolor='rgba(100, 149, 237, 0.1)',
            line=dict(color='#6495ed', width=2, dash='dash'), name='Original'
        ))
        fig_radar.update_layout(
            polar=dict(
                bgcolor='rgba(10,25,47,0.8)',
                radialaxis=dict(visible=True, range=[0, 100], gridcolor='rgba(255,255,255,0.1)'),
                angularaxis=dict(gridcolor='rgba(255,255,255,0.1)')
            ),
            showlegend=True, height=400,
            paper_bgcolor='rgba(0,0,0,0)', font_color='#ccd6f6',
            margin=dict(t=30, b=30)
        )
        st.plotly_chart(fig_radar, use_container_width=True)

    # Interaction Analysis
    st.markdown("#### 🔄 Cross-Category Interaction Effects")
    effects = results['interaction_effects']

    int_col1, int_col2, int_col3 = st.columns(3)
    with int_col1:
        st.markdown(f"""
        <div class="info-box">
            <b>Synergy Effects</b><br>
            Total: <span class="interaction-synergy">{results['total_synergy']:.2f} pts</span><br>
            Ratio: <span class="interaction-synergy">{results['synergy_ratio']:.2f}</span>
        </div>""", unsafe_allow_html=True)
    with int_col2:
        st.markdown(f"""
        <div class="info-box">
            <b>Trade-off Effects</b><br>
            Total: <span class="interaction-tradeoff">{results['total_tradeoff']:.2f} pts</span><br>
            {"Synergies dominate ✅" if results['synergy_ratio'] > 1 else "Trade-offs dominate ⚠️"}
        </div>""", unsafe_allow_html=True)
    with int_col3:
        st.markdown(f"""
        <div class="info-box">
            <b>Heuristic Overall Assessment</b><br>
            Score: <b>{results['heuristic_display_score']:.1f}/100</b><br>
            {"Excellent 🎉" if results['heuristic_display_score'] >= 80 else ("Good 👍" if results['heuristic_display_score'] >= 60 else "Needs Improvement 📈")}
        </div>""", unsafe_allow_html=True)

    # Detailed interaction effects table
    with st.expander("📋 Detailed Interaction Effects", expanded=False):
        interaction_df = pd.DataFrame({
            'Interaction': ['Material → Environmental', 'Environmental → Operational',
                           'Operational → Economic', 'Economic → Material',
                           'Material → Operational', 'Environmental → Economic'],
            'Effect (pts)': [f"{effects['mat_env_effect']:+.2f}", f"{effects['env_op_effect']:+.2f}",
                            f"{effects['op_econ_effect']:+.2f}", f"{effects['econ_mat_effect']:+.2f}",
                            f"{effects['mat_op_effect']:+.2f}", f"{effects['env_econ_effect']:+.2f}"],
            'Type': ['Trade-off' if effects['mat_env_effect'] < 0 else 'Synergy',
                     'Trade-off' if effects['env_op_effect'] < 0 else 'Synergy',
                     'Trade-off' if effects['op_econ_effect'] < 0 else 'Synergy',
                     'Trade-off' if effects['econ_mat_effect'] < 0 else 'Synergy',
                     'Trade-off' if effects['mat_op_effect'] < 0 else 'Synergy',
                     'Trade-off' if effects['env_econ_effect'] < 0 else 'Synergy']
        })
        st.dataframe(interaction_df, use_container_width=True, hide_index=True)

    # Full Report Text
    with st.expander("📄 Full Assessment Report", expanded=False):
        report = f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    ENHANCED MONORAIL SUSTAINABILITY ASSESSMENT RESULTS       ║
╚══════════════════════════════════════════════════════════════════════════════╝

📊 HEURISTIC DISPLAY SCORE: {results['heuristic_display_score']:.1f}/100

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🏗️ MATERIALS ASSESSMENT
   • Material Efficiency Score: {results['material_score']:.1f}/100
   • Concrete Volume: {params['concrete']:.1f} thousand m³
   • Steel Mass: {params['steel']:.1f} thousand tons
   • Aluminum Mass: {params['aluminum']:.1f} thousand tons
   • Wood Volume: {params['wood']:.1f} thousand m³
   • FRP Mass: {params['frp']:.1f} thousand tons
   • Glass Area: {params['glass']:.1f} thousand m²
   • Steel Recycling Rate: {params['steel_recycle']:.1f}%
   • Aluminum Recycling Rate: {params['aluminum_recycle']:.1f}%

🌱 ENVIRONMENTAL ASSESSMENT
   • Environmental Score: {results['environmental_score']:.1f}/100
   • Annual Operational CO₂: {results['annual_co2_operational']:.1f} tons
   • Total Embodied CO₂: {results['total_embodied_co2']:.1f} tons
   • A4 Transport CO₂: {results['lca_results']['a4_transport_co2_tons']:.1f} tons
   • Total Lifecycle CO₂ (Embodied + A4 Transport + Lifetime Operational): {results['total_lifecycle_co2']:.1f} tons
   • Effective Carbon Intensity: {results['effective_carbon_intensity']:.3f} kg CO₂/kWh
   • Total Embodied Energy: {results['total_ee']:.0f} MJ
   • Renewable Energy Share: {params['renewable_share']:.1f}%

⚡ OPERATIONAL ASSESSMENT
   • Operational Score: {results['operational_score']:.1f}/100
   • Energy per Passenger-km: {params['energy_per_pax']:.3f} kWh
   • Daily Passenger-km: {params['daily_pax_km']:.1f} thousand
   • System Availability: {params['availability']:.1f}%

💰 ECONOMIC ASSESSMENT
   • Economic Score: {results['economic_score']:.1f}/100
   • Construction Cost: ${params['construction_cost']:.1f} million
   • Annual Maintenance: ${params['maintenance_cost']:.1f} million
   • Total Jobs Created: {results['total_jobs']:.0f}
   • 50-Year Maintenance (undiscounted): ${results['total_maintenance_cost']:.1f} million

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INTEGRATED SCORING WITH CROSS-CATEGORY INTERACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ORIGINAL → ADJUSTED SCORES:
  Material:      {results['material_score']:.1f} → {results['adjusted_material_score']:.1f} ({results['adjusted_material_score'] - results['material_score']:+.1f})
  Environmental: {results['environmental_score']:.1f} → {results['adjusted_environmental_score']:.1f} ({results['adjusted_environmental_score'] - results['environmental_score']:+.1f})
  Operational:   {results['operational_score']:.1f} → {results['adjusted_operational_score']:.1f} ({results['adjusted_operational_score'] - results['operational_score']:+.1f})
  Economic:      {results['economic_score']:.1f} → {results['adjusted_economic_score']:.1f} ({results['adjusted_economic_score'] - results['economic_score']:+.1f})

Synergy-to-Trade-off Ratio: {results['synergy_ratio']:.2f}

Assessment Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Methodology: Partial process-based LCA (A1-A3 materials + optional A4 transport + B6 operation) + NPV-based LCCA. Chen 2022 is benchmark-only.
"""
        st.code(report, language=None)

        # Export buttons
        exp1, exp2, exp3 = st.columns(3)
        with exp1:
            st.download_button("📥 Download Report (.txt)", report,
                              file_name=f"monorail_report_{datetime.now().strftime('%Y%m%d')}.txt",
                              mime="text/plain")
        with exp2:
            csv_data = pd.DataFrame([
                {'Category': 'LCA', 'Metric': 'Total lifecycle CO₂', 'Value': f"{results['total_lifecycle_co2']:.1f}", 'Unit': 'tons CO₂e'},
                {'Category': 'LCA', 'Metric': 'CO₂ intensity', 'Value': f"{results['co2_kg_per_pkm']:.6f}", 'Unit': 'kg CO₂e/pkm'},
                {'Category': 'LCA', 'Metric': 'Embodied CO₂', 'Value': f"{results['lca_results']['embodied_co2_tons']:.1f}", 'Unit': 'tons CO₂e'},
                {'Category': 'LCA', 'Metric': 'A4 Transport CO₂', 'Value': f"{results['lca_results']['a4_transport_co2_tons']:.1f}", 'Unit': 'tons CO₂e'},
                {'Category': 'LCA', 'Metric': 'Lifetime operational CO₂', 'Value': f"{results['lca_results']['lifetime_operational_co2_tons']:.1f}", 'Unit': 'tons CO₂e'},
                {'Category': 'LCA', 'Metric': 'Embodied Energy', 'Value': f"{results['total_ee']:.0f}", 'Unit': 'MJ'},
                {'Category': 'LCCA', 'Metric': 'LCC NPV Cost', 'Value': f"{results['npv_lcc_m']:.0f}", 'Unit': '$M'},
                {'Category': 'Display-only', 'Metric': 'Heuristic Display Score', 'Value': f"{results['heuristic_display_score']:.1f}", 'Unit': '/100'},
            ]).to_csv(index=False)
            st.download_button("📥 Download CSV", csv_data,
                              file_name=f"monorail_data_{datetime.now().strftime('%Y%m%d')}.csv")
        with exp3:
            excel_buf = io.BytesIO()
            with pd.ExcelWriter(excel_buf, engine='openpyxl') as writer:
                pd.DataFrame({
                    'Metric': [
                        'Total lifecycle CO₂',
                        'CO₂ intensity',
                        'Embodied CO₂',
                        'A4 Transport CO₂',
                        'Lifetime operational CO₂',
                        'Embodied Energy',
                        'LCC NPV Cost',
                        'Heuristic Display Score'
                    ],
                    'Value': [
                        results['total_lifecycle_co2'],
                        results['co2_kg_per_pkm'],
                        results['lca_results']['embodied_co2_tons'],
                        results['lca_results']['a4_transport_co2_tons'],
                        results['lca_results']['lifetime_operational_co2_tons'],
                        results['total_ee'],
                        results['npv_lcc_m'],
                        results['heuristic_display_score']
                    ],
                    'Unit': [
                        'tons CO₂e',
                        'kg CO₂e/pkm',
                        'tons CO₂e',
                        'tons CO₂e',
                        'tons CO₂e',
                        'MJ',
                        '$M',
                        '/100 display-only'
                    ]
                }).to_excel(writer, sheet_name='Summary', index=False)
            st.download_button("📥 Download Excel", excel_buf.getvalue(),
                              file_name=f"monorail_report_{datetime.now().strftime('%Y%m%d')}.xlsx",
                              mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")


# ═══════════════════════════════════════════════════════════════
# TAB 2: BENCHMARK & VALIDATION
# ═══════════════════════════════════════════════════════════════
with tabs[1]:
    st.markdown("### 🔬 Benchmark Validation Against Chen et al. (2022)")
    st.markdown("""
    Compare your assessment results with peer-reviewed monorail LCA studies.
    **Benchmark:** Chen et al. (2022) — Complexity Journal (Q2) — DOI: 10.1155/2022/3872069
    """)

    system_length_km = 96
    chen_total_concrete = CHEN_2022_BENCHMARK['material_intensity_per_km']['concrete_m3'] * system_length_km
    chen_total_steel = CHEN_2022_BENCHMARK['material_intensity_per_km']['steel_tons'] * system_length_km
    chen_total_aluminum = CHEN_2022_BENCHMARK['material_intensity_per_km']['aluminum_tons'] * system_length_km
    chen_embodied_energy_total = CHEN_2022_BENCHMARK['embodied_impact_per_km']['energy_GJ'] * system_length_km
    chen_embodied_carbon_total = CHEN_2022_BENCHMARK['embodied_impact_per_km']['carbon_tons_CO2'] * system_length_km
    chen_operational_energy = CHEN_2022_BENCHMARK['operational_performance']['energy_kwh_per_pkm']
    chen_operational_carbon = CHEN_2022_BENCHMARK['operational_performance']['carbon_kgCO2_per_pkm']

    your_embodied_energy_GJ = results['total_ee'] / 1000.0
    your_operational_carbon_raw = results['energy_per_pax_km'] * results['effective_carbon_intensity']

    def get_status(your_val, bench_val):
        err = abs((your_val - bench_val) / bench_val * 100)
        if err < 10: return '✓ Excellent', 'excellent'
        elif err < 20: return '~ Good', 'good'
        else: return '✗ Review', 'poor'

    comparisons = [
        ('Total Concrete (m³)', chen_total_concrete, results['concrete_volume']),
        ('Total Steel (tons)', chen_total_steel, results['steel_tons']),
        ('Total Aluminum (tons)', chen_total_aluminum, results['aluminum_tons']),
        ('Embodied Energy (GJ)', chen_embodied_energy_total, your_embodied_energy_GJ),
        ('Embodied Carbon (tons CO₂)', chen_embodied_carbon_total, results['total_embodied_co2']),
        ('Energy Intensity (kWh/pkm)', chen_operational_energy, results['energy_per_pax_km']),
        ('Carbon Intensity (kg CO₂/pkm)', chen_operational_carbon, your_operational_carbon_raw),
    ]

    bench_data = []
    excellent_count = good_count = review_count = 0
    for metric, chen_val, your_val in comparisons:
        error_pct = abs((your_val - chen_val) / chen_val * 100) if chen_val != 0 else 0
        status, tag = get_status(your_val, chen_val)
        if tag == 'excellent': excellent_count += 1
        elif tag == 'good': good_count += 1
        else: review_count += 1
        bench_data.append({
            'Metric': metric,
            'Chen 2022': f"{chen_val:,.2f}" if chen_val < 100 else f"{chen_val:,.0f}",
            'Your Tool': f"{your_val:,.2f}" if your_val < 100 else f"{your_val:,.0f}",
            'Difference': f"{your_val - chen_val:+,.2f}" if abs(your_val) < 100 else f"{your_val - chen_val:+,.0f}",
            'Error %': f"{error_pct:.1f}%",
            'Status': status
        })

    bench_df = pd.DataFrame(bench_data)
    st.dataframe(bench_df, use_container_width=True, hide_index=True)

    total_metrics = excellent_count + good_count + review_count
    validation_rate = (excellent_count + good_count) / total_metrics * 100 if total_metrics > 0 else 0

    vc1, vc2, vc3, vc4 = st.columns(4)
    with vc1: st.metric("✓ Excellent (<10%)", excellent_count)
    with vc2: st.metric("~ Good (<20%)", good_count)
    with vc3: st.metric("✗ Review (>20%)", review_count)
    with vc4: st.metric("Validation Rate", f"{validation_rate:.0f}%")


# ═══════════════════════════════════════════════════════════════
# TAB 3: PARETO OPTIMIZATION
# ═══════════════════════════════════════════════════════════════
with tabs[2]:
    st.markdown("### 🎯 Multi-Objective Optimization: Pareto Front Analysis")
    st.warning("Illustrative synthetic scenario visualization; not used in the scientific LCA/LCCA results.")
    st.markdown("Visualize trade-offs between Environmental Impact, Economic Cost, and Technical Performance.")

    if st.button("🔄 Generate Pareto Front", key="pareto_btn"):
        np.random.seed(42)
        n_solutions = 100

        base_co2 = results['total_co2']
        base_cost = results.get('total_cost', base_co2 * 0.01)
        base_score = results.get('sustainability_score', 75)

        co2_values = base_co2 * np.random.uniform(0.85, 1.15, n_solutions)
        cost_values = base_cost * np.random.uniform(0.80, 1.20, n_solutions)
        score_values = base_score * np.random.uniform(0.90, 1.10, n_solutions)

        # Identify Pareto-optimal
        pareto_mask = np.ones(n_solutions, dtype=bool)
        for i in range(n_solutions):
            if not pareto_mask[i]: continue
            for j in range(n_solutions):
                if i == j: continue
                if (co2_values[j] <= co2_values[i] and cost_values[j] <= cost_values[i] and
                    score_values[j] >= score_values[i] and
                    (co2_values[j] < co2_values[i] or cost_values[j] < cost_values[i] or score_values[j] > score_values[i])):
                    pareto_mask[i] = False
                    break

        fig = go.Figure()
        fig.add_trace(go.Scatter3d(
            x=co2_values[pareto_mask], y=cost_values[pareto_mask] / 1e6,
            z=score_values[pareto_mask], mode='markers',
            marker=dict(size=10, color=score_values[pareto_mask], colorscale='Viridis',
                       showscale=True, colorbar=dict(title="Score"), line=dict(color='gold', width=2)),
            name='Pareto Optimal',
            text=[f'CO₂: {c/1000:.1f}k<br>Cost: ${co/1e6:.2f}M<br>Score: {s:.1f}'
                  for c, co, s in zip(co2_values[pareto_mask], cost_values[pareto_mask], score_values[pareto_mask])],
            hoverinfo='text'
        ))
        fig.add_trace(go.Scatter3d(
            x=co2_values[~pareto_mask], y=cost_values[~pareto_mask] / 1e6,
            z=score_values[~pareto_mask], mode='markers',
            marker=dict(size=5, color='lightgray', opacity=0.3), name='Dominated'
        ))
        fig.add_trace(go.Scatter3d(
            x=[base_co2], y=[base_cost / 1e6], z=[base_score], mode='markers',
            marker=dict(size=15, color='red', symbol='diamond', line=dict(color='darkred', width=3)),
            name='Current Solution'
        ))
        fig.update_layout(
            title='3D Pareto Front: Environmental vs Economic vs Performance',
            scene=dict(
                xaxis=dict(title='CO₂ (tons)', backgroundcolor='white'),
                yaxis=dict(title='Cost ($M)', backgroundcolor='white'),
                zaxis=dict(title='Score', backgroundcolor='white'),
                camera=dict(eye=dict(x=1.5, y=1.5, z=1.3))
            ),
            height=700, paper_bgcolor='white', plot_bgcolor='white'
        )
        st.plotly_chart(fig, use_container_width=True)

        n_pareto = np.sum(pareto_mask)
        st.success(f"Found {n_pareto} Pareto-optimal solutions out of {n_solutions} evaluated.")


# ═══════════════════════════════════════════════════════════════
# TAB 4: 12-ELEMENT ANALYSIS (Parallel Coordinates)
# ═══════════════════════════════════════════════════════════════
with tabs[3]:
    st.warning("Illustrative synthetic scenario visualization; not used in the scientific LCA/LCCA results.")
    st.markdown("### 📈 Parallel Coordinates: 12 Sustainability Elements")

    if st.button("📊 Generate Parallel Coordinates", key="parallel_btn"):
        np.random.seed(42)
        n_scenarios = 20
        scenarios_data = []
        for i in range(n_scenarios):
            variation = np.random.uniform(0.9, 1.1)
            scenario = {
                'Concrete Impact': float(np.clip(100 - (results['concrete_volume'] / 10000) * variation, 0, 100)),
                'Steel Impact': float(np.clip(100 - (results['steel_mass'] / 1500) * variation, 0, 100)),
                'Aluminum Impact': float(np.clip(100 - (results['aluminum_mass'] / 75) * variation, 0, 100)),
                'Embodied Energy': float(np.clip(100 - (results['total_ee'] / 100000) * variation, 0, 100)),
                'Carbon Emissions': float(np.clip(100 - (results['total_co2'] / 4000) * variation, 0, 100)),
                'Water Consumption': float(np.clip(np.random.uniform(60, 85) * variation, 0, 100)),
                'Op. Efficiency': float(np.clip(np.random.uniform(70, 95) * variation, 0, 100)),
                'Maintenance': float(np.clip(np.random.uniform(65, 90) * variation, 0, 100)),
                'Safety Rating': float(np.clip(np.random.uniform(80, 98) * variation, 0, 100)),
                'Economic Viability': float(np.clip(np.random.uniform(60, 85) * variation, 0, 100)),
                'Social Impact': float(np.clip(np.random.uniform(55, 80) * variation, 0, 100)),
                'Lifecycle Cost': float(np.clip(100 - (results.get('total_cost', 2500) / 40) * variation, 0, 100))
            }
            scenarios_data.append(scenario)

        df = pd.DataFrame(scenarios_data)
        df['Overall_Score'] = df.mean(axis=1)

        dimensions = [dict(label=col, values=df[col], range=[0, 100]) for col in df.columns[:-1]]

        fig = go.Figure(data=go.Parcoords(
            line=dict(color=df['Overall_Score'], colorscale='RdYlGn', showscale=True, cmin=0, cmax=100,
                     colorbar=dict(title="Overall<br>Score", thickness=20)),
            dimensions=dimensions
        ))
        fig.update_layout(title='12 Sustainability Elements Across Scenarios', height=700, paper_bgcolor='white')
        st.plotly_chart(fig, use_container_width=True)

        best = df[df.columns[:-1]].mean().nlargest(3)
        worst = df[df.columns[:-1]].mean().nsmallest(3)
        bc1, bc2 = st.columns(2)
        with bc1:
            st.markdown("**🏆 Top Performing Elements:**")
            for i, (name, val) in enumerate(best.items()): st.write(f"{i+1}. {name}: {val:.1f}/100")
        with bc2:
            st.markdown("**⚠️ Needs Improvement:**")
            for i, (name, val) in enumerate(worst.items()): st.write(f"{i+1}. {name}: {val:.1f}/100")


# ═══════════════════════════════════════════════════════════════
# TAB 5: UNCERTAINTY ANALYSIS (Monte Carlo)
# ═══════════════════════════════════════════════════════════════
with tabs[4]:
    st.markdown("### 🎲 Scenario-based Monte Carlo Uncertainty")
    st.markdown("Scenario-based Monte Carlo simulation. CV values are scenario assumptions unless documented by EPD/database uncertainty.")

    if st.button("🎲 Run Monte Carlo Analysis", key="mc_btn"):
        n_simulations = 1000
        np.random.seed(42)

        base_co2 = results['total_co2']
        base_energy = results['total_ee']
        base_cost = results.get('total_cost', base_co2 * 0.01)

        concrete_unc = UNCERTAINTY_FACTORS["concrete_factor"]["cv"]
        steel_unc = UNCERTAINTY_FACTORS["steel_factor"]["cv"]
        energy_unc = UNCERTAINTY_FACTORS["energy_factor"]["cv"]
        carbon_unc = UNCERTAINTY_FACTORS["grid_carbon_factor"]["cv"]

        co2_sim, energy_sim, cost_sim = [], [], []
        for _ in range(n_simulations):
            def lognormal_factor(cv, size=1):
                sigma = np.sqrt(np.log(1 + cv**2))
                mu = -0.5 * sigma**2
                return np.random.lognormal(mean=mu, sigma=sigma, size=size)

            cf = lognormal_factor(concrete_unc)[0]
            sf = lognormal_factor(steel_unc)[0]
            ef = lognormal_factor(energy_unc)[0]
            carbf = lognormal_factor(carbon_unc)[0]
            co2_sim.append(base_co2 * cf * carbf)
            energy_sim.append(base_energy * ef)
            cost_sim.append(base_cost * cf * sf)

        co2_sim = np.array(co2_sim)
        energy_sim = np.array(energy_sim)
        cost_sim = np.array(cost_sim)

        fig = make_subplots(rows=3, cols=1,
                           subplot_titles=('CO₂ Emissions', 'Embodied Energy', 'Total Cost'),
                           vertical_spacing=0.12)
        fig.add_trace(go.Histogram(x=co2_sim/1000, nbinsx=50, name='CO₂',
                                    marker=dict(color='rgba(200,50,50,0.6)', line=dict(color='darkred', width=1))), row=1, col=1)
        fig.add_trace(go.Histogram(x=energy_sim/1000, nbinsx=50, name='Energy',
                                    marker=dict(color='rgba(50,100,200,0.6)', line=dict(color='darkblue', width=1))), row=2, col=1)
        fig.add_trace(go.Histogram(x=cost_sim/1e6, nbinsx=50, name='Cost',
                                    marker=dict(color='rgba(50,200,50,0.6)', line=dict(color='darkgreen', width=1))), row=3, col=1)

        co2_ci = (np.percentile(co2_sim, 2.5), np.percentile(co2_sim, 97.5))
        co2_mean = np.mean(co2_sim)
        co2_cv = (np.std(co2_sim) / co2_mean) * 100

        fig.add_vline(x=co2_ci[0]/1000, line_dash="dash", line_color="red", row=1, col=1)
        fig.add_vline(x=co2_ci[1]/1000, line_dash="dash", line_color="red", row=1, col=1)
        fig.add_vline(x=co2_mean/1000, line_color="darkred", line_width=3, row=1, col=1)

        fig.update_layout(title=f'Monte Carlo ({n_simulations} Simulations)', height=900,
                         showlegend=False, paper_bgcolor='white')
        fig.update_xaxes(title_text="CO₂ (k tons)", row=1, col=1)
        fig.update_xaxes(title_text="Energy (GJ)", row=2, col=1)
        fig.update_xaxes(title_text="Cost ($M)", row=3, col=1)
        st.plotly_chart(fig, use_container_width=True)

        uc1, uc2, uc3 = st.columns(3)
        with uc1:
            st.metric("CO₂ 95% CI", f"[{co2_ci[0]/1000:.1f}k, {co2_ci[1]/1000:.1f}k]")
            st.metric("CV", f"{co2_cv:.1f}%")
        with uc2:
            e_ci = (np.percentile(energy_sim, 2.5), np.percentile(energy_sim, 97.5))
            st.metric("Energy 95% CI", f"[{e_ci[0]/1000:.1f}, {e_ci[1]/1000:.1f}] GJ")
        with uc3:
            c_ci = (np.percentile(cost_sim, 2.5), np.percentile(cost_sim, 97.5))
            st.metric("Cost 95% CI", f"[${c_ci[0]/1e6:.2f}M, ${c_ci[1]/1e6:.2f}M]")


# ═══════════════════════════════════════════════════════════════
# TAB 6: 3D SENSITIVITY SURFACE
# ═══════════════════════════════════════════════════════════════
with tabs[5]:
    st.markdown("### 📐 3D Sensitivity Surface: Carbon Intensity × Renewable Energy")

    if st.button("📈 Generate 3D Surface", key="surface_btn"):
        carbon_range = np.linspace(0.2, 0.8, 30)
        renew_range = np.linspace(0, 100, 30)
        X, Y = np.meshgrid(carbon_range, renew_range)
        Z = np.zeros_like(X)

        base_co2 = results['total_co2']
        for i in range(X.shape[0]):
            for j in range(X.shape[1]):
                carbon_factor = X[i, j] / 0.5
                renewable_factor = (100 - Y[i, j]) / (100 - 20)
                Z[i, j] = base_co2 * carbon_factor * renewable_factor

        Z_norm = (Z - Z.min()) / (Z.max() - Z.min()) * 10

        fig = go.Figure(data=[go.Surface(
            x=X, y=Y, z=Z_norm, colorscale='RdYlGn_r',
            colorbar=dict(title="Relative<br>Impact"),
            contours=dict(z=dict(show=True, usecolormap=True, highlightcolor="limegreen", project=dict(z=True))),
            hovertemplate='Carbon: %{x:.2f}<br>Renewable: %{y:.1f}%<br>Impact: %{z:.2f}<extra></extra>'
        )])
        fig.update_layout(
            title='3D Sensitivity: Carbon Intensity vs Renewable Energy',
            scene=dict(
                xaxis=dict(title='Carbon (kg CO₂/kWh)', backgroundcolor="rgb(230,230,230)"),
                yaxis=dict(title='Renewable (%)', backgroundcolor="rgb(230,230,230)"),
                zaxis=dict(title='Relative Impact', backgroundcolor="rgb(230,230,230)"),
                camera=dict(eye=dict(x=1.5, y=1.5, z=1.3))
            ),
            height=800, paper_bgcolor='white'
        )
        st.plotly_chart(fig, use_container_width=True)

        min_idx = np.unravel_index(Z.argmin(), Z.shape)
        st.success(f"Optimal: Carbon = {X[min_idx]:.3f} kg/kWh, Renewable = {Y[min_idx]:.1f}%")


# ═══════════════════════════════════════════════════════════════
# TAB 7: ONE-AT-A-TIME SENSITIVITY ANALYSIS
# ═══════════════════════════════════════════════════════════════
with tabs[6]:
    st.markdown("### 📊 One-at-a-Time Sensitivity Analysis")
    st.caption("Scenario-based OAT sensitivity on Total Lifecycle CO₂ (±10% per variable).")

    def one_at_a_time_sensitivity(params, variable, change_pct=0.10):
        base = run_full_assessment(params)["lca_results"]["total_lifecycle_co2_tons"]
        modified = params.copy()
        modified[variable] = modified[variable] * (1 + change_pct)
        new_val = run_full_assessment(modified)["lca_results"]["total_lifecycle_co2_tons"]
        if base == 0:
            return 0.0
        return ((new_val - base) / base) / change_pct

    var_map = {
        'carbon_intensity': 'Grid Carbon Intensity',
        'energy_per_pax': 'Energy per pax-km',
        'daily_pax_km': 'Daily pax-km',
        'steel': 'Steel quantity',
        'aluminum': 'Aluminum quantity',
        'concrete': 'Concrete quantity',
        'renewable_share': 'Renewable share'
    }

    sens = []
    for k, label in var_map.items():
        val = one_at_a_time_sensitivity(params, k, 0.10)
        sens.append((label, val))

    sens_df = pd.DataFrame(sens, columns=['Variable', 'Sensitivity Index'])
    sens_df['Abs'] = sens_df['Sensitivity Index'].abs()
    sens_df = sens_df.sort_values('Abs', ascending=False)

    fig_sens = go.Figure(go.Bar(
        x=sens_df['Sensitivity Index'],
        y=sens_df['Variable'],
        orientation='h',
        marker_color=['#ff6b6b' if v > 0 else '#64ffda' for v in sens_df['Sensitivity Index']]
    ))
    fig_sens.update_layout(title='OAT Sensitivity Index on Total Lifecycle CO₂', height=450,
                           xaxis_title='((ΔOutput/Output)/(ΔInput/Input))', yaxis_title='Variable')
    st.plotly_chart(fig_sens, use_container_width=True)
    st.dataframe(sens_df[['Variable','Sensitivity Index']], use_container_width=True, hide_index=True)

# TAB 8: URBAN ANALYTICS
# ═══════════════════════════════════════════════════════════════
with tabs[7]:
    st.warning("Illustrative synthetic scenario visualization; not used in the scientific LCA/LCCA results.")
    st.markdown("### 🗺️ Urban Analytics 3D: Spatial Sustainability Assessment")

    case_study = st.selectbox("Select Case Study:", ['Cairo', 'Chongqing', 'Osaka', 'Generic'], key="case_sel")

    if st.button("🗺️ Generate Urban Analytics", key="urban_btn"):
        case_data = {
            'Cairo': {'stations': 22, 'length_km': 54, 'lat_center': 30.0444, 'lon_center': 31.2357, 'population_served': 2000000},
            'Chongqing': {'stations': 45, 'length_km': 67, 'lat_center': 29.5630, 'lon_center': 106.5516, 'population_served': 5000000},
            'Osaka': {'stations': 18, 'length_km': 28, 'lat_center': 34.6937, 'lon_center': 135.5023, 'population_served': 1500000},
            'Generic': {'stations': 25, 'length_km': 40, 'lat_center': 40.7128, 'lon_center': -74.0060, 'population_served': 1000000}
        }
        data = case_data[case_study]
        n_stations = data['stations']

        np.random.seed(42)
        lats = np.linspace(data['lat_center'] - 0.2, data['lat_center'] + 0.2, n_stations) + np.random.normal(0, 0.02, n_stations)
        lons = np.linspace(data['lon_center'] - 0.2, data['lon_center'] + 0.2, n_stations) + np.random.normal(0, 0.02, n_stations)

        station_co2 = results['total_co2'] / n_stations
        co2_per_station = station_co2 * np.random.uniform(0.8, 1.2, n_stations)
        pax_per_station = (data['population_served'] / n_stations) * np.random.uniform(0.7, 1.3, n_stations)

        fig = go.Figure()
        fig.add_trace(go.Scattergeo(
            lat=lats, lon=lons, mode='markers+text',
            marker=dict(size=co2_per_station / np.max(co2_per_station) * 30 + 10,
                       color=co2_per_station, colorscale='RdYlGn_r', showscale=True,
                       colorbar=dict(title="CO₂<br>(tons/yr)"), line=dict(color='black', width=1)),
            text=[f'S{i+1}' for i in range(n_stations)], textposition='top center',
            hovertext=[f'<b>Station S{i+1}</b><br>CO₂: {co2:.0f} t/yr<br>Pax: {int(p):,}/day'
                      for i, (co2, p) in enumerate(zip(co2_per_station, pax_per_station))],
            hoverinfo='text', name='Stations'
        ))
        fig.add_trace(go.Scattergeo(lat=lats, lon=lons, mode='lines',
                                     line=dict(width=3, color='blue'), opacity=0.5, name='Route'))
        fig.update_geos(center=dict(lat=data['lat_center'], lon=data['lon_center']),
                       projection_type='natural earth', showcountries=True, showcoastlines=True,
                       showland=True, landcolor='rgb(243,243,243)')
        fig.update_layout(
            title=f'Urban Analytics: {case_study} Monorail Network ({n_stations} stations | {data["length_km"]} km)',
            height=700, showlegend=True
        )
        st.plotly_chart(fig, use_container_width=True)

        uc1, uc2, uc3 = st.columns(3)
        with uc1:
            st.metric("Total CO₂", f"{np.sum(co2_per_station):,.0f} t/yr")
            st.metric("Avg/Station", f"{np.mean(co2_per_station):,.0f} t/yr")
        with uc2:
            st.metric("Max Station", f"S{np.argmax(co2_per_station)+1} ({co2_per_station[np.argmax(co2_per_station)]:,.0f} t)")
            st.metric("Min Station", f"S{np.argmin(co2_per_station)+1} ({co2_per_station[np.argmin(co2_per_station)]:,.0f} t)")
        with uc3:
            st.metric("Per Capita", f"{np.sum(co2_per_station)/data['population_served']*1000:.2f} kg/person/yr")
            st.metric("Density", f"{n_stations/data['length_km']:.2f} stations/km")


# ═══════════════════════════════════════════════════════════════
# TAB 9: INTERACTION NETWORK
# ═══════════════════════════════════════════════════════════════
with tabs[8]:
    st.markdown("### 🔄 Illustrative Interaction Visualization")
    st.warning("This network is a heuristic visualization only. The coefficients are not validated causal effects and are not used in the core LCA/LCCA results.")

    categories_net = ['Material', 'Environmental', 'Operational', 'Economic']
    angles = np.linspace(0, 2*np.pi, 4, endpoint=False)
    node_x = np.cos(angles)
    node_y = np.sin(angles)

    interactions = [
        ('Material', 'Environmental', effects['mat_env_effect']),
        ('Environmental', 'Operational', effects['env_op_effect']),
        ('Operational', 'Economic', effects['op_econ_effect']),
        ('Economic', 'Material', effects['econ_mat_effect']),
        ('Material', 'Operational', effects['mat_op_effect']),
        ('Environmental', 'Economic', effects['env_econ_effect'])
    ]

    fig_net = go.Figure()
    for fr, to, val in interactions:
        fi = categories_net.index(fr)
        ti = categories_net.index(to)
        color = 'green' if val > 0 else 'red'
        fig_net.add_trace(go.Scatter(
            x=[node_x[fi], node_x[ti], None], y=[node_y[fi], node_y[ti], None],
            mode='lines', line=dict(width=min(abs(val)*2+1, 10), color=color),
            hoverinfo='text', hovertext=f"{fr} → {to}: {val:+.2f} ({'Synergy' if val > 0 else 'Trade-off'})",
            showlegend=False
        ))

    node_colors = ['#3498db', '#2ecc71', '#f39c12', '#e74c3c']
    scores_adj = [results['adjusted_material_score'], results['adjusted_environmental_score'],
                  results['adjusted_operational_score'], results['adjusted_economic_score']]

    fig_net.add_trace(go.Scatter(
        x=node_x, y=node_y, mode='markers+text',
        marker=dict(size=[s*0.5+20 for s in scores_adj], color=node_colors,
                   line=dict(width=3, color='white')),
        text=categories_net, textposition='middle center',
        textfont=dict(size=12, color='white', family='Arial Black'),
        hovertext=[f"<b>{c}</b><br>Score: {s:.1f}" for c, s in zip(categories_net, scores_adj)],
        hoverinfo='text', showlegend=False
    ))

    fig_net.add_trace(go.Scatter(x=[None], y=[None], mode='lines',
                                  line=dict(width=4, color='green'), name='Synergy (+)'))
    fig_net.add_trace(go.Scatter(x=[None], y=[None], mode='lines',
                                  line=dict(width=4, color='red'), name='Trade-off (-)'))

    fig_net.update_layout(
        title='Cross-Category Interaction Network',
        xaxis=dict(showgrid=False, showticklabels=False, zeroline=False, range=[-1.5, 1.5]),
        yaxis=dict(showgrid=False, showticklabels=False, zeroline=False, range=[-1.5, 1.5]),
        plot_bgcolor='#f8f9fa', paper_bgcolor='white', height=700,
        showlegend=True, legend=dict(x=0.02, y=0.98)
    )
    fig_net.add_annotation(
        text=f"<b>Stats</b><br>Synergy: {results['total_synergy']:.2f}<br>"
             f"Trade-off: {results['total_tradeoff']:.2f}<br>Ratio: {results['synergy_ratio']:.2f}",
        xref="paper", yref="paper", x=0.98, y=0.02, xanchor='right', yanchor='bottom',
        showarrow=False, bgcolor='rgba(255,255,255,0.9)', bordercolor='black', borderwidth=1
    )
    st.plotly_chart(fig_net, use_container_width=True)


# ═══════════════════════════════════════════════════════════════
# TAB 10: ABOUT & METHODOLOGY
# ═══════════════════════════════════════════════════════════════
with tabs[9]:
    st.markdown("""
### 📖 Assessment Methodology

---

#### 1. LIFE CYCLE ASSESSMENT (LCA)
- **ISO 14040:2006** — Environmental Management Framework
- **ISO 14044:2006** — LCA Requirements and Guidelines
- **Functional Unit:** 1 passenger-kilometer over 50-year lifecycle
- **System Boundary:** Partial process-based LCA covering A1-A3 material production, optional A4 material transport, and B6 operation. A5 construction, B2-B5 maintenance/replacement, and C1-C4 end-of-life are not yet included.

#### 2. LIFE CYCLE COST ANALYSIS (LCCA)
- **ASTM E917** — Standard Practice for Measuring Life-Cycle Costs
- **Net Present Value (NPV)** methodology
- 50-year economic assessment period

#### 3. HEURISTIC INTEGRATED DISPLAY SCORING
- Dashboard-only visualization score.
- It is not used as an ISO LCA/LCCA result.
- Scientific conclusions should be taken from the LCA and NPV-LCCA outputs.

| Category | Weight | Key Components |
|---|---|---|
| Material Efficiency | 25% | 6 materials + recycling bonuses |
| Environmental | 30% | CO₂, renewable energy, land use, noise |
| Operational | 25% | Time savings, availability, energy efficiency |
| Economic | 20% | Jobs, lifecycle cost, economic multiplier |

#### 4. ILLUSTRATIVE INTERACTION VISUALIZATION
- The interaction network is used only for dashboard visualization.
- The coefficients are heuristic display parameters.
- They are not validated causal effects and are not part of the core LCA/LCCA results.
- SDG interaction literature is used only as conceptual background, not as a numerical source for the coefficients.

#### 5. BENCHMARK VALIDATION
- **Chen et al. (2022)** — Complexity Journal (Q2)
- DOI: [10.1155/2022/3872069](https://doi.org/10.1155/2022/3872069)
- Used only as an external benchmark comparison; no Chen calibration factors are used in the core model.

---

#### SCIENTIFIC REFERENCES

1. ISO 14040:2006 — Environmental Management — Life Cycle Assessment
2. ISO 14044:2006 — Environmental Management — Life Cycle Assessment — Requirements and Guidelines
3. ASTM E917-17 — Standard Practice for Measuring Life-Cycle Costs
4. Chen, J., Wang, H., Li, X. (2022). "Quantifying Carbon Emissions." *Complexity*, 2022, 3872069.
5. Nilsson, M., et al. (2016). "Mapping interactions between SDGs." *Nature*, 534, 320-322. Used as conceptual background only.

---

#### DATA SOURCES
- **Material embodied energy and carbon:** MATERIAL_FACTOR_AUDIT table; Hammond & Jones / ICE legacy energy data + EPD/ICE-aligned A1-A3 carbon factors documented in Supplementary Dataset S1.
- **Operational electricity carbon:** User-defined grid carbon intensity adjusted by renewable share.
- **LCCA:** User-defined construction, maintenance, energy cost, residual value, and discount rate.
- **Recycling credits:** Scenario assumptions unless EPD/EoL allocation evidence is attached.
- **Transport A4:** Scenario-based ton-km calculation using user-selected mode and transport distance.
- **Synthetic visualizations:** Pareto, 12-element, and urban analytics tabs are illustrative only and not part of the scientific LCA/LCCA results.

---

#### HOW TO CITE

```
[Your Name]. (2025). Enhanced Monorail Sustainability Assessment Tool:
Process-based Partial LCA and NPV-based LCCA Framework with Scenario-based Sensitivity Analysis.
Cairo University. Software version 2.0.
```

```bibtex
@software{monorail_lca_2025,
  author = {[Your Name]},
  title = {Enhanced Monorail Sustainability Assessment Tool: Process-based Partial LCA and NPV-based LCCA Framework},
  year = {2025},
  institution = {Cairo University},
  version = {2.0}
}
```
    """)

# ═══════════════════════════════════════════════════════════════
# FOOTER
# ═══════════════════════════════════════════════════════════════
st.markdown("---")
st.markdown(
    f"<div style='text-align:center; color:#8892b0; font-size:0.85rem;'>"
    f"🚝 Enhanced Monorail LCA/LCCA Assessment Tool v2.0 | "
    f"Cairo University | ISO 14040/14044 + ASTM E917 | "
    f"Last run: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    f"</div>", unsafe_allow_html=True
)
